services:
  - type: web
    name: safeguard-advisor-backend
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT"

    envVars:
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY